FROM python:3.9

# Installation des dépendances
RUN pip install --no-cache-dir streamlit pymongo pandas

# Création du dossier de l’application
WORKDIR /app

# Copier le code de l’application
COPY . .

# Exposer le port de Streamlit
EXPOSE 8501

# Lancer Streamlit
CMD ["streamlit", "run", "streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]